apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-management
  labels:
    app: data-management
    version: v0.0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-management
      version: v0.0.1
  template:
    metadata:
      labels:
        app: data-management
        version: v0.0.1
    spec:
      containers:
        - name: data-management
          image: darwin1.azurecr.io/darwin/data-manager
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres123
            - name: POSTGRES_HOST
              value: postgres.db
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: data-management
  labels:
    app: data-management
    version: v0.0.1
spec:
  type: ClusterIP
  selector:
    app: data-management
    version: v0.0.1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: data-management
spec:
  hosts:
    - data-manager.aks.mixerml.com
  gateways:
    - istio-system/common-gw
    - mesh
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 8080
            host: data-management